[package]
name = "parley2"
version = "0.1.0"
edition = "2024"

[features]
default = []
panic_on_handle_drop = []

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3

[dependencies]
parley = { git = "https://github.com/linebender/parley", rev = "93a2faa" }
wgpu = { version = "23", default-features = true }
etagere = "0.2.10"
lru = { version = "0.12.1", default-features = false }
rustc-hash = "2.0"
swash = "0.2.2"
image = "0.25.6"
bytemuck = "1.23.0"
winit = "0.30.9"
lazy_static = "1.5.0"
accesskit = "0.19.0"
peniko = "0.4.0"
arboard = "3.5.0"
slab = "0.4.10"


[dev-dependencies]
pollster = "0.4.0"

[[example]]
name = "basic"
path = "examples/basic.rs"

[[example]]
name = "occlusion"
path = "examples/occlusion.rs"

