[package]
name = "parley_atlas_renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
parley = "0.3"
wgpu = "25"
etagere = "0.2.10"
lru = { version = "0.12.1", default-features = false }
rustc-hash = "2.0"


[dev-dependencies]
image = "0.25.6"
pollster = "0.4.0"
winit = "0.30.9"
